"""Initial migration

Revision ID: cb9e366a1eaf
Revises:
Create Date: 2025-11-03 17:41:45.652377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb9e366a1eaf"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contacts_email"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_id"), table_name="contacts")
    op.drop_table("contacts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "first_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "last_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("date_of_birth", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("information", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("contacts_pkey")),
    )
    op.create_index(op.f("ix_contacts_id"), "contacts", ["id"], unique=False)
    op.create_index(op.f("ix_contacts_email"), "contacts", ["email"], unique=True)
    # ### end Alembic commands ###
